<? include '../include/header.php' ?>
</head>

<body>
<? include '../include/gnb.php' ?>
<div id="wrap" class="study">
  <? include '../include/lnb_'.$fileName[1].'.php' ?>  
  <div id="contents">
    <div id="titleArea" style="background-image:url(../images/title_bg/study.png);">
      <!-- 페이지 네비게이션 h2, 페이지 타이틀 h1, 일반 내용출력 h3 -->
      <h2><?=$siteName?><img src="../images/global/icon_triangle.png" alt="▶" />교육과정<img src="../images/global/icon_triangle.png" alt="▶" /><strong>산업안전보건교육 소개</strong></h2>
      <h1>산업안전보건교육 소개</h1>
    </div>
    <div style="padding:20px; text-align:center;">
      <!--  컨텐츠 이미지 영역 -->
      <!-- <img src="../images/kvoucher/intro_kvoucher.jpg" style="width:100%;" alt="비대면서비스바우처 소개" /> -->
		<!-- Image Map Generated by http://www.image-map.net/ -->
		<img src="../images/lecture/intro_safety_education.jpg" usemap="#imgmap2021129123718">
		<map id="imgmap2021129123718" name="imgmap2021129123718">
		<area shape="rect" alt="" title="" coords="291,2456,544,2526" href="/lecture/?sort01=lecture03" target="" />
		<!-- Created by Online Image Map Editor (http://www.maschek.hu/imagemap/index) --></map>

      <!--  //컨텐츠 이미지 영역 -->
    </div>
    <!-- 동작호출부 -->
    <!-- //동작호출부 -->
  </div>
</div>

<? include '../include/footer.php' ?>